import Footer from '@/components/Footer';
import Header from '@/components/Header';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='flex flex-col w-full max-w-screen-2xl mx-auto'>
        <Header />
        <main className='grow sm:pt-20 pt-28'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
